{
 "title": "Covid 19 NYT",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "state_picker",
    "label": "State",
    "query": "SELECT state FROM states ORDER BY state ASC"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "\n# Public Health Data\n\n\n" },
  {
   "title": "Worldwide Deaths",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 2 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT date, country, latitude, longitude, sum (deaths) as total_deaths\nFROM world\nGROUP BY date, country, latitude, longitude\nORDER BY date DESC, country ASC;"
    }
   ]
  },
  {
   "title": "US Percentage Cases",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT date as time, 100 * cases / (SELECT sum(cases) FROM world WHERE date = numerator_world.date) as percentage\nFROM world numerator_world\nWHERE country = 'US'\nGROUP BY date, cases\nORDER BY date DESC;"
    }
   ]
  },
  {
   "title": "US Percentage Deaths",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT date as time, 100 * deaths / (SELECT sum(deaths) FROM world WHERE date = numerator_world.date) as percentage\nFROM world numerator_world\nWHERE country = 'US'\nGROUP BY date, deaths\nORDER BY date DESC;"
    }
   ]
  },
  {
   "title": "Global vs US Cases",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", sum (cases) as global_cases\nFROM world\nGROUP BY time\nORDER BY time;"
    },
    {
     "rawSql": "SELECT date as \"time\", sum (cases) as us_cases\nFROM world\nWHERE country = 'US'\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Global vs US Deaths",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", sum (deaths) as global_deaths\nFROM world\nGROUP BY time\nORDER BY time;"
    },
    {
     "rawSql": "SELECT date as \"time\", sum (deaths) as us_deaths\nFROM world\nWHERE country = 'US'\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "US Current Cases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT date, sum(cases)\nFROM states\nGROUP BY date\nORDER BY date DESC"
    }
   ]
  },
  {
   "title": "US Current Deaths",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT date, sum(deaths)\nFROM states\nGROUP BY date\nORDER BY date DESC"
    }
   ]
  },
  {
   "title": "US Current Mortality Rate",
   "type": "stat",
   "description": "(Dependent on Testing Efficiency)",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT date, sum(deaths) / sum(cases) AS mortality\nFROM states\nGROUP BY date\nORDER BY date DESC"
    }
   ]
  },
  {
   "title": "National Cases and Deaths",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", sum (cases) as total_cases\nFROM states\nGROUP BY time\nORDER BY time;"
    },
    {
     "rawSql": "SELECT date as \"time\", sum (deaths) as total_deaths\nFROM states\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "National Cases and Deaths (Log Scale)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", sum (cases) as total_cases, sum (deaths) as total_deaths\nFROM states\nGROUP BY time\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Northern and Southern California Cases",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", 'NorCal' AS region, total_cases\nFROM northern_california\nGROUP BY date, region, total_cases\nORDER BY date"
    },
    {
     "rawSql": "SELECT date as \"time\", 'SoCal' AS region, total_cases\nFROM southern_california\nGROUP BY date, region, total_cases\nORDER BY date"
    }
   ]
  },
  {
   "title": "Northern and Southern California Deaths",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", 'NorCal' AS region, total_deaths\nFROM northern_california\nGROUP BY date, region, total_deaths\nORDER BY date"
    },
    {
     "rawSql": "SELECT date as \"time\", 'SoCal' AS region, total_deaths\nFROM southern_california\nGROUP BY date, region, total_deaths\nORDER BY date"
    }
   ]
  },
  {
   "title": "Bay Area Cases",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", 'NorCal' AS region, total_cases\nFROM northern_california\nGROUP BY date, region, total_cases\nORDER BY date"
    }
   ]
  },
  {
   "title": "Bay Area Deaths",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", 'NorCal' AS region, total_deaths\nFROM northern_california\nGROUP BY date, region, total_deaths\nORDER BY date"
    }
   ]
  },
  {
   "title": "Bay Area vs NYC Cases",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", 'NorCal' AS region, total_cases\nFROM northern_california\nGROUP BY date, region, total_cases\nORDER BY date"
    },
    {
     "rawSql": "SELECT date as \"time\", 'New York' AS region, sum(cases) as total_cases\nFROM counties\nWHERE county = 'New York City' AND state = 'New York'\nGROUP BY date\nORDER BY date"
    }
   ]
  },
  {
   "title": "Bay Area vs NYC Deaths",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", 'NorCal' AS region, total_deaths\nFROM northern_california\nGROUP BY date, region, total_deaths\nORDER BY date"
    },
    {
     "rawSql": "SELECT date as \"time\", 'New York' AS region, sum(deaths) as total_deaths\nFROM counties\nWHERE county = 'New York City' AND state = 'New York'\nGROUP BY date\nORDER BY date"
    }
   ]
  },
  {
   "title": "Key New Hotspot Deaths",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", state, deaths\nFROM states\nWHERE state IN ('Louisiana', 'Georgia', 'Michigan', 'Florida')\nGROUP BY time, state, deaths\nORDER BY time, state ASC;"
    }
   ]
  },
  {
   "title": "State by State Cases",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", state, cases\nFROM states\nWHERE state IN ($state_picker)\nGROUP BY time, state, cases\nORDER BY time, state ASC;"
    }
   ]
  },
  {
   "title": "State by State Cases (Log Scale)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", state, cases\nFROM states\nWHERE state IN ($state_picker)\nGROUP BY time, state, cases\nORDER BY time, state ASC;"
    }
   ]
  },
  {
   "title": "State by State Deaths",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", state, deaths\nFROM states\nWHERE state in ($state_picker)\nGROUP BY time, state, deaths\nORDER BY time, state ASC;"
    }
   ]
  },
  {
   "title": "State by State Deaths (Log Scale)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", state, deaths\nFROM states\nWHERE state in ($state_picker)\nGROUP BY time, state, deaths\nORDER BY time, state ASC;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 83 },
   "content": "\n# Political Considerations\n\n\n\n"
  },
  {
   "title": "Trump vs Clinton County Cases",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT counties.date as \"time\", sum (counties.cases) as trump_cases\nFROM counties\nWHERE counties.fips IN (SELECT fips FROM trump_counties)\nGROUP BY date\nORDER BY date DESC;"
    },
    {
     "rawSql": "SELECT counties.date as \"time\", sum (counties.cases) as clinton_cases\nFROM counties\nWHERE counties.fips IN (SELECT fips FROM clinton_counties)\nGROUP BY date\nORDER BY date DESC;"
    }
   ]
  },
  {
   "title": "Trump vs Clinton County Deaths",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT counties.date as \"time\", sum (counties.deaths) as trump_deaths\nFROM counties\nWHERE counties.fips IN (SELECT fips FROM trump_counties)\nGROUP BY date\nORDER BY date DESC;"
    },
    {
     "rawSql": "SELECT counties.date as \"time\", sum (counties.deaths) as clinton_deaths\nFROM counties\nWHERE counties.fips IN (SELECT fips FROM clinton_counties)\nGROUP BY date\nORDER BY date DESC;"
    }
   ]
  },
  {
   "title": "2020 Battleground County Cases and Deaths",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as time, sum(total_cases) as tc\nFROM battleground_counties\nGROUP BY date;"
    },
    {
     "rawSql": "SELECT date as time, sum(total_deaths) as td\nFROM battleground_counties\nGROUP BY date;"
    }
   ]
  },
  {
   "title": "National Unemployment Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 107 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('30d', date) AS time,\n       (100 * sum(unemployed) / sum (population)) AS value\nFROM employment\nGROUP BY time\nORDER BY time ASC;\n"
    }
   ]
  },
  {
   "title": "California Unemployment Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 107 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('30d', date) AS time,\n       (100 * sum(unemployed) / sum (population)) AS value\nFROM employment\nWHERE employment.fips IN (SELECT fips FROM counties WHERE counties.state = 'California')\nGROUP BY time;\n"
    }
   ]
  },
  {
   "title": "Selected States Unemployment Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 107 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('30d', date) AS time,\n       (100 * sum(unemployed) / sum (population)) AS value\nFROM employment\nWHERE employment.fips IN (SELECT fips FROM counties WHERE state IN ($state_picker))\nGROUP BY time;\n"
    }
   ]
  },
  {
   "title": "2020 Battleground Counties Unemployment Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 107 },
   "targets": [
    {
     "rawSql": "SELECT time_bucket('30d', date) AS time,\n       (100 * sum(unemployed) / sum (population)) AS value\nFROM employment\nWHERE employment.fips IN (SELECT fips FROM battleground_counties)\nGROUP BY time;\n"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 112 }, "content": "\n# Raw Data\n\n\n\n" },
  {
   "title": "State Cases Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "rawSql": "SELECT state, date as time, cases\nFROM states\nWHERE state in ($state_picker)\nGROUP BY state, date, cases\nORDER BY state ASC, date DESC;"
    }
   ]
  },
  {
   "title": "State Deaths Table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 125 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT state, date as time, deaths\nFROM states\nWHERE state IN ($state_picker)\nGROUP BY state, time, deaths\nORDER BY time DESC, state ASC;",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Table of Cases and Deaths by State",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {
     "rawSql": "SELECT state, date, cases, deaths\nFROM states\nWHERE date >= current_date - interval '10' day and\n      state IN ($state_picker)\nGROUP BY state, date, cases, deaths\nORDER BY state ASC, date DESC;"
    }
   ]
  }
 ]
}